version: '2'

services:
  app:
    image: node:5
    working_dir: /work
    command: ./run
    volumes:
      - ./app:/work
      - node5-npm-cache:/work/node_modules
    ports:
      - "8000:8000"
    expose:
      - "8000"

  test:
    image: node:5
    working_dir: /work
    command: ./run
    volumes:
      - ./test:/work
      - node5-npm-cache:/work/node_modules
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome:2.53.0
    depends_on:
      - app

volumes:
  node5-npm-cache:
    external: true
