app:
  image: node:5
  working_dir: /cwd
  command: ./run
  volumes:
    - ./app:/cwd
  expose:
    - "8000"

test:
  image: node:5
  working_dir: /cwd
  command: ./run
  volumes:
    - ./tests:/cwd
  links:
    - selenium

selenium:
  image: selenium/standalone-chrome:2.48.2
  links:
    - app
