app:
  image: node:5
  working_dir: /cwd
  command: ./run
  volumes:
    - ./app:/cwd
  volumes_from:
    - cache
  expose:
    - "8000"

test:
  image: node:5
  working_dir: /cwd
  command: ./run
  volumes:
    - ./test:/cwd
  volumes_from:
    - cache
  links:
    - selenium

selenium:
  image: selenium/standalone-chrome:2.48.2
  links:
    - app

cache:
  image: node:5
  volumes:
    - ./node_modules:/cwd/node_modules
